#!/bin/bash

# script to report UPS state changes...

e=`date +%s`
d=`date`
logRoot='/var/log/ups'
log="$logRoot.$e"
host=`cat /etc/hostname`

echo "$0 $* RUN $d" > $log 2>&1
echo "" >> $log 2>&1

# dump apcupsd log...
tail /var/log/apcupsd.events >> $log 2>&1
echo "" >> $log 2>&1

# remove logs over 30 days old...
find $logRoot.* -mtime +30 | 2>/dev/null xargs -r rm -- >> $log 2>&1

# move log to base file and email to sysop...
cp $log "$logRoot.log"
cat $log | /usr/local/bin/mailto.py "$host UPS script..."

