#!/bin/bash

# script to setup terminal multiplexer with session for multiusers
# each user defines their setup in /home/$USER/.tmux.init
# session named for user

### BEGIN INIT INFO
# Provides:  tmux-$USER
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start and Stop
# Description:  tmux initialization script
### END INIT INFO

# parameters...
NAME=tmux
SCRIPT=/usr/local/bin/tmux
XARGS="kill-server"

# find users  with .tmux.init
declare -a who
for u in $( ls /home ); do
    if [ -e /home/$u/.tmux.init ]; then
        who[${#who}]=$u
    fi
done

case "$1" in
        start)
                echo "Starting $SCRIPT service..."
                for u in $who; do
                        su $u -c "$SCRIPT -c /home/$u/.tmux.init"
                        echo "Started: /home/$u/.tmux.init"
                done
                sleep 1
                $0 status
        ;;
        stop)
                echo "Shutting down $SCRIPT service..."
                su $USER -c "$SCRIPT $XARGS"
                $0 status
        ;;
        status)
                STATUS=$(ps aux | sed -n -e 1p -e "/$NAME/I"p | grep -v $0 | grep -v sed)
                echo "$STATUS"
        ;;
        restart)
                $0 stop; $0 start
        ;;
        auto)
                case "$2" in
                        start)
                                /usr/sbin/update-rc.d $NAME defaults
                        ;;
                        stop)
                                /usr/sbin/update-rc.d $NAME remove
                        ;;
                        *)
                                $0
                        ;;
                esac
        ;;
        *)
                echo "Usage: $0 start|stop|status|restart|(auto start|auto)|stop"
                exit 1
        ;;
esac

